<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], []],
    'formations' => [[], ['_controller' => 'App\\Controller\\FormationsController::index'], [], [['text', '/formations']], [], []],
    'formations.sort' => [['champ', 'ordre'], ['_controller' => 'App\\Controller\\FormationsController::sort'], [], [['variable', '/', '[^/]++', 'ordre'], ['variable', '/', '[^/]++', 'champ'], ['text', '/formations/tri']], [], []],
    'formations.niveau' => [['valeur'], ['_controller' => 'App\\Controller\\FormationsController::sortNiveau'], [], [['variable', '/', '[^/]++', 'valeur'], ['text', '/formations/triNiveau']], [], []],
    'formations.findallcontain' => [['champ'], ['_controller' => 'App\\Controller\\FormationsController::findAllContain'], [], [['variable', '/', '[^/]++', 'champ'], ['text', '/formations/recherche']], [], []],
    'formations.showone' => [['id'], ['_controller' => 'App\\Controller\\FormationsController::showOne'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/formations/formation']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'admin.formations' => [[], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::index'], [], [['text', '/admin']], [], []],
    'admin.formation.suppr' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::suppr'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/suppr']], [], []],
    'admin.formation.edit' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::edit'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/edit']], [], []],
    'admin.formation.ajout' => [[], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::ajout'], [], [['text', '/admin/ajout']], [], []],
    'admin.formations.sort' => [['champ', 'ordre'], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::sort'], [], [['variable', '/', '[^/]++', 'ordre'], ['variable', '/', '[^/]++', 'champ'], ['text', '/admin/formations/tri']], [], []],
    'admin.formations.niveau' => [['valeur'], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::sortNiveau'], [], [['variable', '/', '[^/]++', 'valeur'], ['text', '/admin/formations/triNiveau']], [], []],
    'admin.formations.findallcontain' => [['champ'], ['_controller' => 'App\\Controller\\admin\\AdminFormationsController::findAllContain'], [], [['variable', '/', '[^/]++', 'champ'], ['text', '/admin/formations/recherche']], [], []],
    'admin.niveaux' => [[], ['_controller' => 'App\\Controller\\admin\\AdminNiveauxController::index'], [], [['text', '/admin/niveaux']], [], []],
    'admin.niveau.suppr' => [['id'], ['_controller' => 'App\\Controller\\admin\\AdminNiveauxController::suppr'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/admin/niveau/suppr']], [], []],
    'admin.niveau.ajout' => [[], ['_controller' => 'App\\Controller\\admin\\AdminNiveauxController::ajoutNiveau'], [], [['text', '/admin/niveaux/ajout']], [], []],
];
